[features]
seeds = false

[programs.localnet]
imso_claim = "CgWrLM8UqxNvaHUKVfVFjW7XSiQNYP4qyk9SoCbfcXPP"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/numisman/Documents/projects/imso/keypairs/imsoClaim/imRDfkDNhnaT5nbVZKLD5jjQQ5WZzedqxZtB2X6hUFW.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/imso_claim"]

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "../metaplex-program-library/target/deploy/mpl_token_metadata.so"
