[features]
seeds = false

[programs.localnet]
redemptionV0 = "tfre5zcihbycEcr1xo67saNvovdmXhQFXPM2obQqRjP"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = ".anchor/ledger/validator-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/redemptionV0"]

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "../metaplex-program-library/target/deploy/mpl_token_metadata.so"
